"""
Export utilities for XTream credentials
"""

import json
import m3u8
from typing import List
from models import XtreamCredential

class XtreamExporter:
    """Exports XTream credentials to various formats"""
    
    @staticmethod
    def to_m3u(credentials: List[XtreamCredential], filename: str = "xtream_urls.m3u"):
        """Export credentials to M3U playlist format"""
        with open(filename, 'w', encoding='utf-8') as f:
            f.write("#EXTM3U\n")
            f.write("# Generated by urlscan.io XTream scraper\n")
            f.write(f"# Total URLs: {len(credentials)}\n\n")
            
            for cred in credentials:
                # Add validation status to comment
                status = "✓ VALID" if cred.is_valid else "✗ UNVALIDATED" if cred.is_valid is None else "✗ INVALID"
                f.write(f"#EXTINF:-1,{cred.domain} XTream IPTV [{status}]\n")
                f.write(f"{cred.xtream_url}\n")
        
        print(f"Exported {len(credentials)} URLs to {filename}")
    
    @staticmethod
    def to_json(credentials: List[XtreamCredential], filename: str = "xtream_credentials.json"):
        """Export credentials to JSON format with full details"""
        data = {
            'metadata': {
                'total_credentials': len(credentials),
                'valid_credentials': len([c for c in credentials if c.is_valid]),
                'export_date': credentials[0].validation_date.isoformat() if credentials and credentials[0].validation_date else None,
                'source': 'urlscan.io XTream scraper'
            },
            'credentials': [cred.to_dict() for cred in credentials]
        }
        
        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        
        print(f"Exported {len(credentials)} credentials to {filename}")
    
    @staticmethod
    def to_txt(credentials: List[XtreamCredential], filename: str = "xtream_urls.txt"):
        """Export credentials to simple text format"""
        with open(filename, 'w', encoding='utf-8') as f:
            f.write("# XTream IPTV URLs\n")
            f.write(f"# Generated: {len(credentials)} URLs\n\n")
            
            for cred in credentials:
                status = "VALID" if cred.is_valid else "UNVALIDATED" if cred.is_valid is None else "INVALID"
                f.write(f"# {cred.domain}:{cred.port}/{cred.username} [{status}]\n")
                f.write(f"{cred.xtream_url}\n\n")
        
        print(f"Exported {len(credentials)} URLs to {filename}")
    
    @staticmethod
    def to_csv(credentials: List[XtreamCredential], filename: str = "xtream_credentials.csv"):
        """Export credentials to CSV format"""
        import csv
        
        with open(filename, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            
            # Write header
            writer.writerow([
                'Domain', 'Port', 'Username', 'Password', 'XTream_URL', 
                'Original_Redirect', 'Scan_ID', 'Scan_Date', 'Page_URL',
                'Is_Valid', 'Validation_Date', 'Active_Connections', 'Max_Connections'
            ])
            
            # Write data
            for cred in credentials:
                user_info = cred.user_info or {}
                writer.writerow([
                    cred.domain,
                    cred.port,
                    cred.username,
                    cred.password,
                    cred.xtream_url,
                    cred.original_redirect,
                    cred.scan_id,
                    cred.scan_date,
                    cred.page_url,
                    cred.is_valid,
                    cred.validation_date.isoformat() if cred.validation_date else '',
                    user_info.get('active_cons', ''),
                    user_info.get('max_connections', '')
                ])
        
        print(f"Exported {len(credentials)} credentials to {filename}")
